# Generated by Django 4.0.3 on 2022-04-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country_id',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer_id',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='number_id',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
